spring.application.name=faceandbody

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/faceandbody}
spring.datasource.username=${DB_USERNAME:appuser}
spring.datasource.password=${DB_PASSWORD:apppassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:FaceAndBodySecretKey2026SuperLongKeyPerHMAC512AlmenoConQuestoSiamo}
jwt.expiration=${JWT_EXPIRATION:86400000}